export const DEFAULT_BULK_FORM = {
  name: "",
  sku: "",
  description: "",
  categoryId: "",
  packagingType: "25 KG Poly Sacks",
  unitsPerPackage: 1,
  packagesPerPallet: 40,
  leadTimeDays: 2,
  originCountry: "India",
  images: ["https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=800&q=80"],
  countries: {
    US: {
      countryCode: "US",
      currencyCode: "USD",
      currencySymbol: "$",
      name: "United States",
      flag: "🇺🇸",
      isAvailable: true,
      moq: 20,
      stock: 3000,
      basePrice: 25.0,
      tiers: [
        { minQuantity: 20, maxQuantity: 100, price: 25.0 },
        { minQuantity: 101, maxQuantity: 500, price: 22.0 },
        { minQuantity: 501, maxQuantity: null, price: 18.75 },
      ],
    },
    CA: {
      countryCode: "CA",
      currencyCode: "CAD",
      currencySymbol: "CA$",
      name: "Canada",
      flag: "🇨🇦",
      isAvailable: true,
      moq: 20,
      stock: 2000,
      basePrice: 33.75,
      tiers: [
        { minQuantity: 20, maxQuantity: 100, price: 33.75 },
        { minQuantity: 101, maxQuantity: 500, price: 29.70 },
        { minQuantity: 501, maxQuantity: null, price: 25.30 },
      ],
    },
    IN: {
      countryCode: "IN",
      currencyCode: "INR",
      currencySymbol: "₹",
      name: "India",
      flag: "🇮🇳",
      isAvailable: true,
      moq: 50,
      stock: 10000,
      basePrice: 1800,
      tiers: [
        { minQuantity: 50, maxQuantity: 200, price: 1800 },
        { minQuantity: 201, maxQuantity: 1000, price: 1584 },
        { minQuantity: 1001, maxQuantity: null, price: 1350 },
      ],
    },
  },
};
