const id = { type: "string", minLength: 1 };
const idParams = { type: "object", required: ["id"], properties: { id } };

export const businessBody = {
  type: "object", required: ["businessName", "businessEmail", "businessPhone", "countryCode", "address", "contactPersonName"], additionalProperties: false,
  properties: {
    businessName: { type: "string", minLength: 2, maxLength: 200 }, businessEmail: { type: "string", format: "email" }, businessPhone: { type: "string", minLength: 5, maxLength: 40 },
    taxRegistrationNumber: { type: ["string", "null"], maxLength: 100 }, registrationNumber: { type: ["string", "null"], maxLength: 100 }, countryCode: { type: "string", minLength: 2, maxLength: 10 }, address: { type: "string", minLength: 5, maxLength: 500 }, contactPersonName: { type: "string", minLength: 2, maxLength: 150 }
  }
};
const tier = { type: "object", required: ["minQuantity", "price"], additionalProperties: false, properties: { minQuantity: { type: "integer", minimum: 1 }, maxQuantity: { type: ["integer", "null"], minimum: 1 }, price: { type: ["number", "string"], minimum: 0 } } };
const countryPrice = { type: "object", required: ["countryCode", "currencyCode", "moq", "tiers"], additionalProperties: false, properties: { countryCode: { type: "string", minLength: 2 }, currencyCode: { type: "string", minLength: 3 }, moq: { type: "integer", minimum: 1 }, stock: { type: "integer", minimum: 0 }, isAvailable: { type: "boolean" }, tiers: { type: "array", minItems: 1, items: tier } } };
const variant = { type: "object", required: ["sku"], additionalProperties: false, properties: { name: { type: ["string", "null"] }, sku: { type: "string", minLength: 1 }, attributes: { type: ["object", "null"] }, isActive: { type: "boolean" }, countryPrices: { type: "array", items: countryPrice } } };
export const productBody = { type: "object", required: ["name", "type"], additionalProperties: false, properties: { name: { type: "string", minLength: 2, maxLength: 200 }, slug: { type: "string", minLength: 2, maxLength: 220 }, sku: { type: ["string", "null"] }, description: { type: ["string", "null"] }, category: { type: ["string", "null"] }, brand: { type: ["string", "null"] }, type: { type: "string", enum: ["SIMPLE", "VARIABLE"] }, isActive: { type: "boolean" }, images: { type: "array", items: { type: "object", required: ["mediaAssetId"], additionalProperties: false, properties: { mediaAssetId: id, isPrimary: { type: "boolean" }, sortOrder: { type: "integer", minimum: 0 } } } }, countryPrices: { type: "array", items: countryPrice }, variants: { type: "array", items: variant } } };
export const cartItemBody = { type: "object", required: ["productId", "quantity", "countryCode"], additionalProperties: false, properties: { productId: id, variantId: { type: ["string", "null"] }, quantity: { type: "integer", minimum: 1 }, countryCode: { type: "string", minLength: 2 } } };
export const addressBody = { type: "object", required: ["label", "contactName", "phone", "addressLine1", "city", "postalCode", "countryCode"], additionalProperties: false, properties: { label: { type: "string", minLength: 1 }, contactName: { type: "string", minLength: 2 }, phone: { type: "string", minLength: 5 }, addressLine1: { type: "string", minLength: 2 }, addressLine2: { type: ["string", "null"] }, city: { type: "string", minLength: 2 }, state: { type: ["string", "null"] }, postalCode: { type: "string", minLength: 2 }, countryCode: { type: "string", minLength: 2 }, isDefault: { type: "boolean" } } };
export const pageQuery = { type: "object", properties: { page: { type: "integer", minimum: 1 }, limit: { type: "integer", minimum: 1, maximum: 100 }, search: { type: "string" }, countryCode: { type: "string" }, status: { type: "string" }, isActive: { type: "boolean" }, from: { type: "string", format: "date-time" }, to: { type: "string", format: "date-time" } } };
export { idParams };
