export const MOCK_CATEGORIES = [
  { id: "cat-1", name: "Soil & Growing Media", slug: "soil-and-growing-media", count: 24 },
  { id: "cat-2", name: "Pots & Planters", slug: "pots-and-planters", count: 48 },
  { id: "cat-3", name: "Live Plants & Foliage", slug: "live-plants-and-foliage", count: 65 },
  { id: "cat-4", name: "Organic Fertilizers", slug: "organic-fertilizers", count: 18 },
  { id: "cat-5", name: "Commercial Irrigation", slug: "commercial-irrigation", count: 32 },
];

export const MOCK_PRODUCTS = [
  {
    id: "prod-1",
    name: "Premium Organic Garden Soil (50 KG Sack)",
    slug: "premium-garden-soil",
    sku: "SOIL-50KG-SACK",
    category: "Soil & Growing Media",
    categoryId: "cat-1",
    brand: "Vanom Agro",
    rating: 4.9,
    reviewsCount: 142,
    image: "https://images.unsplash.com/photo-1585336261026-7f81498b584d?auto=format&fit=crop&w=800&q=80",
    description: "Heavy-duty 50 KG sack of enriched organic garden soil with bio-active compost, peat moss, and micro-nutrients. Formulated for high-yield agriculture, landscaping, and bulk nursery cultivation.",
    stock: 2450,
    packaging: {
      unitName: "Sack",
      weightKg: 50,
      dimensionsCm: "80 x 45 x 20",
      palletQuantity: 40,
      palletWeightKg: 2000,
    },
    pricing: {
      IN: {
        currency: "INR",
        symbol: "₹",
        retailPrice: 499,
        wholesaleTiers: [
          { minQuantity: 20, maxQuantity: 49, unitPrice: 420 },
          { minQuantity: 50, maxQuantity: 99, unitPrice: 390 },
          { minQuantity: 100, maxQuantity: null, unitPrice: 350 },
        ],
        moq: 20,
      },
      US: {
        currency: "USD",
        symbol: "$",
        retailPrice: 19.99,
        wholesaleTiers: [
          { minQuantity: 20, maxQuantity: 49, unitPrice: 16.50 },
          { minQuantity: 50, maxQuantity: 99, unitPrice: 14.90 },
          { minQuantity: 100, maxQuantity: null, unitPrice: 13.50 },
        ],
        moq: 20,
      },
      GB: {
        currency: "GBP",
        symbol: "£",
        retailPrice: 17.99,
        wholesaleTiers: [
          { minQuantity: 20, maxQuantity: 49, unitPrice: 14.90 },
          { minQuantity: 50, maxQuantity: 99, unitPrice: 13.40 },
          { minQuantity: 100, maxQuantity: null, unitPrice: 12.20 },
        ],
        moq: 20,
      },
    },
  },
  {
    id: "prod-2",
    name: "Architectural Ceramic Planter (Box of 12)",
    slug: "architectural-ceramic-planter",
    sku: "POT-CERAMIC-BOX12",
    category: "Pots & Planters",
    categoryId: "cat-2",
    brand: "TerraCraft",
    rating: 4.8,
    reviewsCount: 89,
    image: "https://images.unsplash.com/photo-1485955900006-10f4d324d411?auto=format&fit=crop&w=800&q=80",
    description: "Commercial grade handcrafted matte ceramic planters with drainage holes and saucers. Packaged in shock-absorbent corrugated bulk cartons.",
    stock: 890,
    packaging: {
      unitName: "Box (12 pcs)",
      weightKg: 18,
      dimensionsCm: "60 x 40 x 40",
      palletQuantity: 24,
      palletWeightKg: 432,
    },
    pricing: {
      IN: {
        currency: "INR",
        symbol: "₹",
        retailPrice: 1299,
        wholesaleTiers: [
          { minQuantity: 10, maxQuantity: 29, unitPrice: 1050 },
          { minQuantity: 30, maxQuantity: 79, unitPrice: 950 },
          { minQuantity: 80, maxQuantity: null, unitPrice: 850 },
        ],
        moq: 10,
      },
      US: {
        currency: "USD",
        symbol: "$",
        retailPrice: 49.99,
        wholesaleTiers: [
          { minQuantity: 10, maxQuantity: 29, unitPrice: 42.00 },
          { minQuantity: 30, maxQuantity: 79, unitPrice: 38.00 },
          { minQuantity: 80, maxQuantity: null, unitPrice: 34.00 },
        ],
        moq: 10,
      },
      GB: {
        currency: "GBP",
        symbol: "£",
        retailPrice: 39.99,
        wholesaleTiers: [
          { minQuantity: 10, maxQuantity: 29, unitPrice: 34.00 },
          { minQuantity: 30, maxQuantity: 79, unitPrice: 30.50 },
          { minQuantity: 80, maxQuantity: null, unitPrice: 27.50 },
        ],
        moq: 10,
      },
    },
  },
  {
    id: "prod-3",
    name: "Indoor Foliage Fiddle-Leaf Fig (Master Crate of 6)",
    slug: "fiddle-leaf-fig-crate",
    sku: "PLNT-FLF-CRATE6",
    category: "Live Plants & Foliage",
    categoryId: "cat-3",
    brand: "Verdant Nursery",
    rating: 4.7,
    reviewsCount: 56,
    image: "https://images.unsplash.com/photo-1545241047-6083a3684587?auto=format&fit=crop&w=800&q=80",
    description: "Acclimatized indoor Ficus Lyrata potted plants in nursery grow containers. Temperature-monitored wooden crate packaging.",
    stock: 350,
    packaging: {
      unitName: "Crate (6 pots)",
      weightKg: 25,
      dimensionsCm: "120 x 80 x 60",
      palletQuantity: 8,
      palletWeightKg: 200,
    },
    pricing: {
      IN: {
        currency: "INR",
        symbol: "₹",
        retailPrice: 2499,
        wholesaleTiers: [
          { minQuantity: 5, maxQuantity: 14, unitPrice: 2100 },
          { minQuantity: 15, maxQuantity: 39, unitPrice: 1850 },
          { minQuantity: 40, maxQuantity: null, unitPrice: 1650 },
        ],
        moq: 5,
      },
      US: {
        currency: "USD",
        symbol: "$",
        retailPrice: 89.99,
        wholesaleTiers: [
          { minQuantity: 5, maxQuantity: 14, unitPrice: 75.00 },
          { minQuantity: 15, maxQuantity: 39, unitPrice: 68.00 },
          { minQuantity: 40, maxQuantity: null, unitPrice: 59.00 },
        ],
        moq: 5,
      },
      GB: {
        currency: "GBP",
        symbol: "£",
        retailPrice: 75.00,
        wholesaleTiers: [
          { minQuantity: 5, maxQuantity: 14, unitPrice: 62.50 },
          { minQuantity: 15, maxQuantity: 39, unitPrice: 56.00 },
          { minQuantity: 40, maxQuantity: null, unitPrice: 49.00 },
        ],
        moq: 5,
      },
    },
  },
  {
    id: "prod-4",
    name: "Pure Cold-Pressed Neem Oil Cake (25 KG Bag)",
    slug: "neem-oil-cake-25kg",
    sku: "FERT-NEEM-25KG",
    category: "Organic Fertilizers",
    categoryId: "cat-4",
    brand: "Vanom Agro",
    rating: 4.9,
    reviewsCount: 112,
    image: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=800&q=80",
    description: "100% natural organic soil amendment and root protection fertilizer rich in NPK and azadirachtin.",
    stock: 1600,
    packaging: {
      unitName: "Bag (25 KG)",
      weightKg: 25,
      dimensionsCm: "70 x 40 x 15",
      palletQuantity: 60,
      palletWeightKg: 1500,
    },
    pricing: {
      IN: {
        currency: "INR",
        symbol: "₹",
        retailPrice: 799,
        wholesaleTiers: [
          { minQuantity: 15, maxQuantity: 44, unitPrice: 650 },
          { minQuantity: 45, maxQuantity: 89, unitPrice: 590 },
          { minQuantity: 90, maxQuantity: null, unitPrice: 520 },
        ],
        moq: 15,
      },
      US: {
        currency: "USD",
        symbol: "$",
        retailPrice: 28.50,
        wholesaleTiers: [
          { minQuantity: 15, maxQuantity: 44, unitPrice: 23.00 },
          { minQuantity: 45, maxQuantity: 89, unitPrice: 20.50 },
          { minQuantity: 90, maxQuantity: null, unitPrice: 18.00 },
        ],
        moq: 15,
      },
      GB: {
        currency: "GBP",
        symbol: "£",
        retailPrice: 24.00,
        wholesaleTiers: [
          { minQuantity: 15, maxQuantity: 44, unitPrice: 19.50 },
          { minQuantity: 45, maxQuantity: 89, unitPrice: 17.50 },
          { minQuantity: 90, maxQuantity: null, unitPrice: 15.20 },
        ],
        moq: 15,
      },
    },
  },
];

export const MOCK_COMPANIES = [
  {
    id: "comp-1",
    legalName: "AgroWholesale India Pvt Ltd",
    tradingName: "AgroWholesale India",
    registrationNumber: "U01100MH2020PTC345678",
    taxId: "27AAACA1234A1Z1",
    country: "India",
    countryCode: "IN",
    status: "APPROVED",
    creditLimit: 500000,
    availableCredit: 385000,
    paymentTerms: "NET_30",
    primaryContact: "Rajesh Kulkarni",
    email: "buyer@agrowholesale.in",
    phone: "+91 98200 12345",
    addresses: [
      { id: "addr-1", type: "SHIPPING", line1: "Warehouse 4, Agro Logistics Park", city: "Navi Mumbai", state: "Maharashtra", postalCode: "400705", country: "India", isDefault: true },
      { id: "addr-2", type: "BILLING", line1: "Suite 302, Green Business Hub", city: "Mumbai", state: "Maharashtra", postalCode: "400051", country: "India", isDefault: true },
    ],
    members: [
      { id: "mem-1", name: "Rajesh Kulkarni", email: "buyer@agrowholesale.in", role: "COMPANY_ADMIN", isPrimary: true },
      { id: "mem-2", name: "Sunil Verma", email: "procurement@agrowholesale.in", role: "COMPANY_BUYER", isPrimary: false },
    ],
    documents: [
      { id: "doc-1", name: "GST_Certificate_2026.pdf", type: "TAX_CERTIFICATE", status: "VERIFIED", uploadedAt: "2026-01-15T10:00:00Z" },
      { id: "doc-2", name: "Certificate_of_Incorporation.pdf", type: "BUSINESS_REGISTRATION", status: "VERIFIED", uploadedAt: "2026-01-15T10:05:00Z" },
    ],
  },
  {
    id: "comp-2",
    legalName: "GreenHaven Landscaping LLC",
    tradingName: "GreenHaven Landscaping",
    registrationNumber: "US-DE-987654",
    taxId: "EIN-82-9384721",
    country: "United States",
    countryCode: "US",
    status: "UNDER_REVIEW",
    creditLimit: 25000,
    availableCredit: 25000,
    paymentTerms: "NET_15",
    primaryContact: "David Miller",
    email: "david@greenhavenlandscapes.com",
    phone: "+1 214 555 0192",
    addresses: [
      { id: "addr-3", type: "SHIPPING", line1: "742 Evergreen Terrace", city: "Dallas", state: "Texas", postalCode: "75201", country: "United States", isDefault: true },
    ],
    members: [
      { id: "mem-3", name: "David Miller", email: "david@greenhavenlandscapes.com", role: "COMPANY_ADMIN", isPrimary: true },
    ],
    documents: [
      { id: "doc-3", name: "IRS_W9_Form.pdf", type: "TAX_CERTIFICATE", status: "UNDER_REVIEW", uploadedAt: "2026-02-10T14:30:00Z" },
      { id: "doc-4", name: "Delaware_LLC_Registration.pdf", type: "BUSINESS_REGISTRATION", status: "UNDER_REVIEW", uploadedAt: "2026-02-10T14:32:00Z" },
    ],
  },
];

export const MOCK_ORDERS = [
  {
    id: "ord-101",
    orderNumber: "ORD-20260228-8921",
    type: "B2C",
    createdAt: "2026-02-27T14:20:00Z",
    status: "DELIVERED",
    currency: "INR",
    symbol: "₹",
    subtotal: 998,
    taxAmount: 179.64,
    shippingCost: 50,
    totalAmount: 1227.64,
    itemsCount: 2,
    shippingAddress: {
      name: "Ramesh Sharma",
      line1: "Flat 402, Lotus Heights",
      city: "Bengaluru",
      state: "Karnataka",
      postalCode: "560001",
      country: "India",
    },
    items: [
      { id: "oi-1", name: "Premium Organic Garden Soil (50 KG Sack)", sku: "SOIL-50KG-SACK", quantity: 2, unitPrice: 499, subtotal: 998, image: "https://images.unsplash.com/photo-1585336261026-7f81498b584d?auto=format&fit=crop&w=400&q=80" },
    ],
    timeline: [
      { status: "PLACED", label: "Order Placed", date: "2026-02-27 14:20" },
      { status: "CONFIRMED", label: "Payment Confirmed", date: "2026-02-27 14:21" },
      { status: "PACKED", label: "Packed at Warehouse", date: "2026-02-27 18:00" },
      { status: "SHIPPED", label: "Out with Express Delivery", date: "2026-02-28 09:30" },
      { status: "DELIVERED", label: "Delivered Successfully", date: "2026-02-28 13:45" },
    ],
  },
  {
    id: "ord-102",
    orderNumber: "ORD-20260228-9410",
    poNumber: "PO-AGRO-2026-04",
    type: "B2B",
    companyName: "AgroWholesale India Pvt Ltd",
    createdAt: "2026-02-28T10:15:00Z",
    status: "PROCESSING",
    currency: "INR",
    symbol: "₹",
    subtotal: 70000, // 200 sacks @ ₹350 (Tier 3)
    taxAmount: 12600, // 18% GST
    shippingCost: 3500, // Freight Pallet
    totalAmount: 86100,
    paymentTerms: "NET_30",
    itemsCount: 200,
    shippingAddress: {
      name: "AgroWholesale Logistics Depot",
      line1: "Warehouse 4, Agro Logistics Park",
      city: "Navi Mumbai",
      state: "Maharashtra",
      postalCode: "400705",
      country: "India",
    },
    items: [
      { id: "oi-2", name: "Premium Organic Garden Soil (50 KG Sack)", sku: "SOIL-50KG-SACK", quantity: 200, unitPrice: 350, subtotal: 70000, packaging: "5 Pallets (40 Sacks / Pallet)", image: "https://images.unsplash.com/photo-1585336261026-7f81498b584d?auto=format&fit=crop&w=400&q=80" },
    ],
    timeline: [
      { status: "PLACED", label: "Purchase Order Received", date: "2026-02-28 10:15" },
      { status: "CONFIRMED", label: "Credit Terms Verified (NET 30)", date: "2026-02-28 10:16" },
      { status: "PROCESSING", label: "Allocated to Mumbai Central Warehouse", date: "2026-02-28 11:00" },
    ],
  },
];

export const MOCK_QUOTES = [
  {
    id: "qte-201",
    quoteNumber: "QTE-20260228-1094",
    companyName: "AgroWholesale India Pvt Ltd",
    status: "QUOTED",
    version: 2,
    createdAt: "2026-02-25T09:00:00Z",
    validUntil: "2026-03-15T23:59:59Z",
    currency: "INR",
    symbol: "₹",
    subtotal: 140000,
    discountAmount: 7000, // 5% bulk concession
    taxAmount: 23940,
    shippingCost: 6000,
    totalAmount: 162940,
    notes: "Special contract pricing for Q1 Spring Planting season. Palletized delivery scheduled over 2 drops.",
    items: [
      { id: "qi-1", name: "Premium Organic Garden Soil (50 KG Sack)", sku: "SOIL-50KG-SACK", quantity: 400, unitPrice: 350, subtotal: 140000, requestedDeliveryDate: "2026-03-10" },
    ],
  },
  {
    id: "qte-202",
    quoteNumber: "QTE-20260226-0812",
    companyName: "GreenHaven Landscaping LLC",
    status: "UNDER_REVIEW",
    version: 1,
    createdAt: "2026-02-26T16:45:00Z",
    validUntil: "2026-03-12T23:59:59Z",
    currency: "USD",
    symbol: "$",
    subtotal: 12240,
    discountAmount: 0,
    taxAmount: 1009.80,
    shippingCost: 850,
    totalAmount: 14099.80,
    notes: "Direct site delivery for commercial botanical garden installation in North Dallas.",
    items: [
      { id: "qi-2", name: "Architectural Ceramic Planter (Box of 12)", sku: "POT-CERAMIC-BOX12", quantity: 360, unitPrice: 34.00, subtotal: 12240, requestedDeliveryDate: "2026-03-20" },
    ],
  },
];

export const MOCK_ADMIN_METRICS = {
  revenueToday: "₹3,48,200",
  revenueGrowth: "+18.4%",
  activeOrdersCount: 42,
  b2bOrdersCount: 14,
  pendingCompanyVerifications: 3,
  pendingQuotesCount: 5,
  lowStockAlertsCount: 2,
  totalCustomers: 18450,
  totalB2BCompanies: 128,
};
