const INITIAL_CATEGORIES = [
  { id: "cat-1", name: "Electronics", slug: "electronics", count: 245, description: "Laptops, audio, smart watches, tablets and gadgets." },
  { id: "cat-2", name: "Home & Living", slug: "home-and-living", count: 180, description: "Furniture, decor, lighting and indoor plants." },
  { id: "cat-3", name: "Kitchen & Dining", slug: "kitchen-and-dining", count: 120, description: "Air fryers, mixer grinders, cookware and appliances." },
  { id: "cat-4", name: "Beauty & Personal Care", slug: "beauty-and-personal-care", count: 96, description: "Skincare, grooming, fragrance and cosmetics." },
  { id: "cat-5", name: "Health & Wellness", slug: "health-and-wellness", count: 85, description: "Fitness trackers, supplements, organic essentials." },
  { id: "cat-6", name: "Toys & Baby", slug: "toys-and-baby", count: 64, description: "Educational toys, baby care and nursery essentials." },
  { id: "cat-7", name: "Sports & Fitness", slug: "sports-and-fitness", count: 72, description: "Gym equipment, smart wearables and outdoor gear." },
  { id: "cat-8", name: "Stationery & Office", slug: "stationery-and-office", count: 54, description: "Desk setups, notebooks, writing and office supply." },
];

const INITIAL_PRODUCTS = [
  {
    id: "lenovo-ideapad-slim-5",
    name: "Lenovo IdeaPad Slim 5 15.6\" Laptop",
    slug: "lenovo-ideapad-slim-5",
    sku: "83E8001TIN",
    category: "Electronics",
    categoryId: "cat-1",
    brand: "Lenovo",
    rating: 4.8,
    reviewsCount: 2349,
    price: 42990,
    mrp: 56999,
    discount: 24,
    badge: "Bestseller",
    specs: "Intel Core i5 13th Gen | 16GB RAM | 512GB SSD | Windows 11 Home",
    image: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=800&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80",
    ],
    description: "13th Gen Intel Core i5-13420H Processor (8 Cores, up to 4.6 GHz) with 16GB LPDDR5 RAM and 512GB ultra-fast SSD. Crisp 15.6\" Full HD IPS Anti-glare Display with sleek cloud grey aluminum chassis.",
    stock: 45,
    highlights: [
      { label: "Processor", value: "Intel Core i5 13th Gen" },
      { label: "RAM", value: "16 GB LPDDR5" },
      { label: "Storage", value: "512 GB SSD" },
      { label: "Display", value: "15.6\" FHD (1920 × 1080)" },
      { label: "Graphics", value: "Intel Iris Xe Graphics" },
      { label: "OS", value: "Windows 11 Home" },
      { label: "Battery", value: "Up to 10 hours" },
      { label: "Weight", value: "1.6 kg" },
    ],
    features: [
      "13th Gen Intel Core i5-13420H Processor (8 Cores, up to 4.6 GHz)",
      "16GB LPDDR5 RAM for smooth multitasking",
      "512GB SSD for faster performance and ample storage",
      "15.6\" Full HD IPS Anti-glare Display",
      "Intel Iris Xe Graphics",
      "Windows 11 Home with lifetime validity",
      "Backlit Keyboard, Fingerprint Reader, and HD Webcam",
      "Sleek and lightweight design (1.6 kg)",
    ],
    specifications: {
      Brand: "Lenovo",
      Series: "IdeaPad Slim 5",
      Model: "83E8001TIN",
      Colour: "Cloud Grey",
      "Form Factor": "Thin and Light",
      "Item Weight": "1.6 kg",
      "Item Dimensions": "35.9 × 23.6 × 1.79 cm",
      "Country of Origin": "China",
      Warranty: "1 Year Onsite Warranty",
    },
    pricing: {
      IN: { currency: "INR", symbol: "₹", retailPrice: 42990, mrp: 56999 },
      US: { currency: "USD", symbol: "$", retailPrice: 549, mrp: 720 },
      GB: { currency: "GBP", symbol: "£", retailPrice: 439, mrp: 575 },
    },
  },
  {
    id: "asus-tuf-gaming-f15",
    name: "ASUS TUF Gaming F15",
    slug: "asus-tuf-gaming-f15",
    sku: "FX506HF-HN024W",
    category: "Electronics",
    categoryId: "cat-1",
    brand: "ASUS",
    rating: 4.6,
    reviewsCount: 1982,
    price: 59990,
    mrp: 74999,
    discount: 20,
    badge: "New",
    specs: "Intel Core i5 13th Gen | 16GB | 512GB SSD | RTX 3050 | 15.6\"",
    image: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&w=800&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?auto=format&fit=crop&w=800&q=80",
    ],
    description: "Built for serious gaming and high durability. Equipped with NVIDIA GeForce RTX 3050 graphics, high-refresh 144Hz IPS display, and dual-fan cooling.",
    stock: 28,
    highlights: [
      { label: "Processor", value: "Intel Core i5 13th Gen" },
      { label: "RAM", value: "16 GB DDR4 3200MHz" },
      { label: "Storage", value: "512 GB PCIe 4.0 SSD" },
      { label: "Display", value: "15.6\" 144Hz FHD IPS" },
      { label: "Graphics", value: "NVIDIA RTX 3050 4GB" },
      { label: "OS", value: "Windows 11 Home" },
      { label: "Battery", value: "Up to 8 hours" },
      { label: "Weight", value: "2.3 kg" },
    ],
    features: [
      "NVIDIA GeForce RTX 3050 4GB GDDR6 Graphics",
      "144Hz Adaptive-Sync Gaming Display with anti-glare",
      "RGB Backlit Gaming Keyboard rated for 20 million keystrokes",
      "Self-cleaning Dual Cooling Fans with anti-dust technology",
      "Military-Grade MIL-STD-810H durability standard",
    ],
    specifications: {
      Brand: "ASUS",
      Series: "TUF Gaming F15",
      Model: "FX506HF-HN024W",
      Colour: "Graphite Black",
      "Form Factor": "Gaming Laptop",
      "Item Weight": "2.3 kg",
      "Item Dimensions": "35.9 × 25.6 × 2.45 cm",
      "Country of Origin": "China",
      Warranty: "1 Year International Warranty",
    },
    pricing: {
      IN: { currency: "INR", symbol: "₹", retailPrice: 59990, mrp: 74999 },
      US: { currency: "USD", symbol: "$", retailPrice: 749, mrp: 940 },
      GB: { currency: "GBP", symbol: "£", retailPrice: 599, mrp: 750 },
    },
  },
  {
    id: "hp-pavilion-15",
    name: "HP Pavilion 15 Laptop",
    slug: "hp-pavilion-15",
    sku: "15-eg3027TU",
    category: "Electronics",
    categoryId: "cat-1",
    brand: "HP",
    rating: 4.7,
    reviewsCount: 1431,
    price: 44990,
    mrp: 62999,
    discount: 29,
    badge: "Trending",
    specs: "Intel Core i5 12th Gen | 16GB | 512GB SSD | 15.6\" FHD",
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=800&q=80",
    ],
    description: "Compact, premium build with Audio by B&O, micro-edge Full HD screen, fast charging, and fingerprint reader for effortless work and study.",
    stock: 60,
    highlights: [
      { label: "Processor", value: "Intel Core i5 12th Gen" },
      { label: "RAM", value: "16 GB DDR4" },
      { label: "Storage", value: "512 GB SSD" },
      { label: "Display", value: "15.6\" Micro-edge FHD" },
      { label: "Graphics", value: "Intel Iris Xe Graphics" },
      { label: "OS", value: "Windows 11 Home" },
      { label: "Battery", value: "Up to 9 hours" },
      { label: "Weight", value: "1.75 kg" },
    ],
    features: [
      "Crystal clear micro-edge IPS display with 250 nits brightness",
      "Audio by Bang & Olufsen with dual stereo speakers",
      "HP Fast Charge: 0 to 50% in approximately 45 minutes",
      "Backlit full-size keyboard with integrated numeric keypad",
    ],
    specifications: {
      Brand: "HP",
      Series: "Pavilion 15",
      Model: "15-eg3027TU",
      Colour: "Natural Silver",
      "Form Factor": "Thin and Light",
      "Item Weight": "1.75 kg",
      "Item Dimensions": "36.0 × 23.4 × 1.79 cm",
      "Country of Origin": "China",
      Warranty: "1 Year Onsite Warranty",
    },
    pricing: {
      IN: { currency: "INR", symbol: "₹", retailPrice: 44990, mrp: 62999 },
      US: { currency: "USD", symbol: "$", retailPrice: 569, mrp: 799 },
      GB: { currency: "GBP", symbol: "£", retailPrice: 459, mrp: 639 },
    },
  },
  {
    id: "dell-inspiron-14",
    name: "Dell Inspiron 14",
    slug: "dell-inspiron-14",
    sku: "IN5430-D14",
    category: "Electronics",
    categoryId: "cat-1",
    brand: "Dell",
    rating: 4.5,
    reviewsCount: 2104,
    price: 43990,
    mrp: 56999,
    discount: 23,
    badge: null,
    specs: "Intel Core i5 13th Gen | 16GB | 512GB SSD | 14\" FHD",
    image: "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?auto=format&fit=crop&w=800&q=80",
    description: "Sleek 14-inch form factor with 16:10 aspect ratio display, Waves MaxxAudio Pro, express charge, and durable aluminum lid.",
    stock: 35,
    highlights: [
      { label: "Processor", value: "Intel Core i5 13th Gen" },
      { label: "RAM", value: "16 GB LPDDR5" },
      { label: "Storage", value: "512 GB SSD" },
      { label: "Display", value: "14.0\" FHD+ (1920 × 1200)" },
      { label: "Graphics", value: "Intel Iris Xe" },
      { label: "OS", value: "Windows 11 Home" },
      { label: "Battery", value: "Up to 11 hours" },
      { label: "Weight", value: "1.5 kg" },
    ],
    features: [
      "16:10 display ratio providing more vertical screen real estate",
      "Spill-resistant backlit keyboard with precision touchpad",
      "Dell ComfortView software reducing blue light emissions",
      "FHD webcam with dual microphones and temporal noise reduction",
    ],
    specifications: {
      Brand: "Dell",
      Series: "Inspiron 14",
      Model: "IN5430-D14",
      Colour: "Platinum Silver",
      "Form Factor": "Compact Laptop",
      "Item Weight": "1.5 kg",
      "Item Dimensions": "31.4 × 22.7 × 1.64 cm",
      "Country of Origin": "China",
      Warranty: "1 Year Premium Support",
    },
    pricing: {
      IN: { currency: "INR", symbol: "₹", retailPrice: 43990, mrp: 56999 },
      US: { currency: "USD", symbol: "$", retailPrice: 559, mrp: 720 },
      GB: { currency: "GBP", symbol: "£", retailPrice: 449, mrp: 579 },
    },
  },
  {
    id: "apple-macbook-air-m2",
    name: "Apple MacBook Air M2",
    slug: "apple-macbook-air-m2",
    sku: "MLY33HN/A",
    category: "Electronics",
    categoryId: "cat-1",
    brand: "Apple",
    rating: 4.9,
    reviewsCount: 3982,
    price: 99900,
    mrp: 119900,
    discount: 17,
    badge: null,
    specs: "Apple M2 | 8GB | 256GB SSD | 13.6\" Liquid Retina",
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80",
    description: "Strikingly thin design with Apple M2 chip, brilliant 13.6-inch Liquid Retina display, 1080p FaceTime HD camera, and up to 18 hours of battery life.",
    stock: 50,
    highlights: [
      { label: "Processor", value: "Apple M2 8-Core Chip" },
      { label: "RAM", value: "8 GB Unified Memory" },
      { label: "Storage", value: "256 GB SSD" },
      { label: "Display", value: "13.6\" Liquid Retina with True Tone" },
      { label: "Graphics", value: "8-Core GPU" },
      { label: "OS", value: "macOS Sequoia" },
      { label: "Battery", value: "Up to 18 hours" },
      { label: "Weight", value: "1.24 kg" },
    ],
    features: [
      "Fanless silent operation under heavy workloads",
      "MagSafe 3 charging port with color-matched braided cable",
      "Four-speaker sound system with Spatial Audio",
      "Touch ID fingerprint sensor for secure unlocking and Apple Pay",
    ],
    specifications: {
      Brand: "Apple",
      Series: "MacBook Air",
      Model: "MLY33HN/A",
      Colour: "Midnight",
      "Form Factor": "Ultraportable",
      "Item Weight": "1.24 kg",
      "Item Dimensions": "30.41 × 21.5 × 1.13 cm",
      "Country of Origin": "China",
      Warranty: "1 Year Apple Limited Warranty",
    },
    pricing: {
      IN: { currency: "INR", symbol: "₹", retailPrice: 99900, mrp: 119900 },
      US: { currency: "USD", symbol: "$", retailPrice: 1099, mrp: 1299 },
      GB: { currency: "GBP", symbol: "£", retailPrice: 999, mrp: 1199 },
    },
  },
  {
    id: "philips-air-fryer-4-1l",
    name: "Philips Air Fryer 4.1L (Rapid Air Tech)",
    slug: "philips-air-fryer-4-1l",
    sku: "HD9200/90",
    category: "Kitchen & Dining",
    categoryId: "cat-3",
    brand: "Philips",
    rating: 4.8,
    reviewsCount: 2340,
    price: 3499,
    mrp: 5299,
    discount: 42,
    badge: "Bestseller",
    specs: "Rapid Air Technology | 1400W | Dishwasher Safe",
    image: "https://images.unsplash.com/photo-1556909172-8c2f041fca1e?auto=format&fit=crop&w=800&q=80",
    description: "Healthy frying with Rapid Air Technology. Fry with up to 90% less fat. Features adjustable temperature & time control with recipe app integration.",
    stock: 120,
    highlights: [
      { label: "Capacity", value: "4.1 Litres" },
      { label: "Power", value: "1400 Watts" },
      { label: "Technology", value: "Rapid Air" },
      { label: "Cleaning", value: "Dishwasher Safe" },
      { label: "Auto Shut-off", value: "Yes" },
      { label: "Timer", value: "Up to 60 min" },
      { label: "Temperature", value: "Up to 200°C" },
      { label: "Weight", value: "4.5 kg" },
    ],
    features: [
      "Rapid Air Technology swirls hot air to create delicious foods with little to no added oil",
      "Integrated timer allows you to preset cooking times of up to 60 minutes",
      "Fully adjustable temperature control lets you preset the best heat setting",
      "All removable parts are dishwasher safe with QuickClean basket",
    ],
    specifications: {
      Brand: "Philips",
      Series: "Essential Collection",
      Model: "HD9200/90",
      Colour: "Black",
      "Item Weight": "4.5 kg",
      "Item Dimensions": "36.0 × 26.4 × 29.5 cm",
      "Country of Origin": "India",
      Warranty: "2 Years Philips Warranty",
    },
    pricing: {
      IN: { currency: "INR", symbol: "₹", retailPrice: 3499, mrp: 5299 },
      US: { currency: "USD", symbol: "$", retailPrice: 49.99, mrp: 79.99 },
      GB: { currency: "GBP", symbol: "£", retailPrice: 39.99, mrp: 64.99 },
    },
  },
  {
    id: "prestige-mixer-grinder-750w",
    name: "Prestige Mixer Grinder 750W (3 Stainless Jars)",
    slug: "prestige-mixer-grinder-750w",
    sku: "IRIS-750W",
    category: "Kitchen & Dining",
    categoryId: "cat-3",
    brand: "Prestige",
    rating: 4.7,
    reviewsCount: 9764,
    price: 2299,
    mrp: 3429,
    discount: 34,
    badge: "Bestseller",
    specs: "750W Copper Motor | 3 Stainless Steel Jars | Overload Protection",
    image: "https://images.unsplash.com/photo-1570222094114-d054a817e56b?auto=format&fit=crop&w=800&q=80",
    description: "Powerful 750-watt motor capable of grinding tough ingredients like whole spices and batters with ease. Comes with 3 heavy-duty stainless steel jars.",
    stock: 95,
    highlights: [
      { label: "Motor", value: "750W Pure Copper" },
      { label: "Jars", value: "3 Stainless Steel" },
      { label: "Blade", value: "Super Sharp Multi-blade" },
      { label: "Safety", value: "Overload Protector" },
      { label: "Speed", value: "3 Speed + Pulse" },
      { label: "Body", value: "Shockproof ABS" },
      { label: "Cord", value: "1.5m PVC" },
      { label: "Weight", value: "5.2 kg" },
    ],
    features: [
      "Pure copper winding motor for heavy-duty daily blending",
      "Ergonomically designed jar handles with sturdy grip",
      "Flow breaker design in jars for superfine grinding",
      "Overload protection switch to protect motor from burning",
    ],
    specifications: {
      Brand: "Prestige",
      Series: "Iris Classic",
      Model: "IRIS-750W",
      Colour: "White & Blue",
      "Item Weight": "5.2 kg",
      "Country of Origin": "India",
      Warranty: "2 Years Prestige Warranty",
    },
    pricing: {
      IN: { currency: "INR", symbol: "₹", retailPrice: 2299, mrp: 3429 },
      US: { currency: "USD", symbol: "$", retailPrice: 34.99, mrp: 49.99 },
      GB: { currency: "GBP", symbol: "£", retailPrice: 27.99, mrp: 39.99 },
    },
  },
  {
    id: "noise-buds-vs104",
    name: "Noise Buds VS104 True Wireless Earbuds",
    slug: "noise-buds-vs104",
    sku: "AUD-NOISE-VS104",
    category: "Electronics",
    categoryId: "cat-1",
    brand: "Noise",
    rating: 4.4,
    reviewsCount: 8493,
    price: 1499,
    mrp: 2999,
    discount: 50,
    badge: null,
    specs: "45 Hours Playtime | Quad Mic ENC | 13mm Driver | Instacharge",
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80",
    description: "45 hours total playtime with ultra-low latency gaming mode, 13mm speaker drivers, and Environmental Noise Cancellation for crystal-clear calling.",
    stock: 150,
    highlights: [
      { label: "Playtime", value: "Up to 45 Hours" },
      { label: "Driver", value: "13mm Dynamic" },
      { label: "Mic", value: "Quad Mic with ENC" },
      { label: "Latency", value: "Low Latency 50ms" },
      { label: "Charging", value: "Instacharge (10m = 200m)" },
      { label: "Bluetooth", value: "v5.3 Hyper Sync" },
      { label: "Waterproof", value: "IPX5 Sweat Resistance" },
      { label: "Weight", value: "38g Case" },
    ],
    features: [
      "Instacharge gives 200 minutes of playtime in just 10 minutes of charging",
      "Quad mic system with Environmental Noise Cancellation (ENC)",
      "13mm dynamic drivers delivering deep bass and crisp vocals",
      "IPX5 water-resistance for sweat and gym workouts",
    ],
    specifications: {
      Brand: "Noise",
      Series: "Buds VS Series",
      Model: "VS104-CHARCOAL",
      Colour: "Charcoal Black",
      "Item Weight": "38 g",
      "Country of Origin": "India",
      Warranty: "1 Year Noise Warranty",
    },
    pricing: {
      IN: { currency: "INR", symbol: "₹", retailPrice: 1499, mrp: 2999 },
      US: { currency: "USD", symbol: "$", retailPrice: 19.99, mrp: 39.99 },
      GB: { currency: "GBP", symbol: "£", retailPrice: 16.99, mrp: 32.99 },
    },
  },
  {
    id: "boat-smartwatch",
    name: "boAt Wave Call Smartwatch (1.69\" HD Display)",
    slug: "boat-smartwatch",
    sku: "BOAT-WAVE-CALL",
    category: "Electronics",
    categoryId: "cat-1",
    brand: "boAt",
    rating: 4.5,
    reviewsCount: 4170,
    price: 4999,
    mrp: 7999,
    discount: 38,
    badge: null,
    specs: "Bluetooth Calling | 1.69\" HD Display | HR & SpO2 Monitoring",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80",
    description: "Premium Bluetooth calling smartwatch with vibrant curved HD display, 550 nits brightness, comprehensive health suite, and 150+ watch faces.",
    stock: 80,
    highlights: [
      { label: "Display", value: "1.69\" HD Curved" },
      { label: "Calling", value: "Bluetooth Dialpad" },
      { label: "Health", value: "Heart Rate & SpO2" },
      { label: "Battery", value: "Up to 7 Days" },
      { label: "Modes", value: "100+ Sports Modes" },
      { label: "Waterproof", value: "IP68 Dust & Splash" },
      { label: "Watchfaces", value: "150+ Cloud Faces" },
      { label: "Weight", value: "45 g" },
    ],
    features: [
      "Ultra-clear Bluetooth calling with built-in speaker and sensitive mic",
      "1.69\" HD full-touch display with 550 nits peak brightness",
      "Continuous heart rate tracking, SpO2 blood oxygen, and sleep monitoring",
      "IP68 dust and water resistance for all-weather workouts",
    ],
    specifications: {
      Brand: "boAt",
      Series: "Wave Call",
      Model: "WAVE-CALL-PRO",
      Colour: "Pitch Black",
      "Item Weight": "45 g",
      "Country of Origin": "India",
      Warranty: "1 Year boAt Warranty",
    },
    pricing: {
      IN: { currency: "INR", symbol: "₹", retailPrice: 4999, mrp: 7999 },
      US: { currency: "USD", symbol: "$", retailPrice: 65.00, mrp: 99.00 },
      GB: { currency: "GBP", symbol: "£", retailPrice: 52.00, mrp: 79.00 },
    },
  },
  {
    id: "live-indoor-plant",
    name: "Live Indoor Areca Palm & Air Purifying Plant",
    slug: "live-indoor-plant",
    sku: "PLNT-ARECA-01",
    category: "Home & Living",
    categoryId: "cat-2",
    brand: "GreenFlora",
    rating: 4.9,
    reviewsCount: 2873,
    price: 499,
    mrp: 799,
    discount: 38,
    badge: null,
    specs: "NASA Certified Air Purifier | Self-Watering Pot Included",
    image: "https://images.unsplash.com/photo-1485955900006-10f4d324d411?auto=format&fit=crop&w=800&q=80",
    description: "Lush green live indoor air purifying plant in a premium designer self-watering ceramic pot. Naturally removes indoor toxins and enhances ambient humidity.",
    stock: 200,
    highlights: [
      { label: "Type", value: "Live Potted Plant" },
      { label: "Pot", value: "Self-watering Ceramic" },
      { label: "Sunlight", value: "Indirect Bright Light" },
      { label: "Watering", value: "Once a Week" },
      { label: "Purification", value: "NASA Certified" },
      { label: "Height", value: "12 - 15 Inches" },
      { label: "Maintenance", value: "Low / Beginner" },
      { label: "Weight", value: "1.2 kg" },
    ],
    features: [
      "Natural humidifier and pollutant remover for bedrooms and office desks",
      "Includes premium self-watering decorative pot with drainage saucer",
      "Low maintenance, thrives in medium to low indirect indoor light",
      "Care guide and organic soil mixture included",
    ],
    specifications: {
      Brand: "GreenFlora",
      Series: "Pure Air Collection",
      Model: "PLNT-ARECA-01",
      Colour: "Lush Emerald Green",
      "Item Weight": "1.2 kg",
      "Country of Origin": "India",
      Warranty: "7 Days Healthy Transit Guarantee",
    },
    pricing: {
      IN: { currency: "INR", symbol: "₹", retailPrice: 499, mrp: 799 },
      US: { currency: "USD", symbol: "$", retailPrice: 9.99, mrp: 14.99 },
      GB: { currency: "GBP", symbol: "£", retailPrice: 7.99, mrp: 12.99 },
    },
  },
];

// In-memory live store with LocalStorage persistence for realistic Admin CRUD
const STORAGE_KEYS = {
  PRODUCTS: "vanom_mock_products_v4",
  CATEGORIES: "vanom_mock_categories_v4",
};

export { INITIAL_PRODUCTS, INITIAL_CATEGORIES };

export const getLiveProducts = () => {
  try {
    const saved = localStorage.getItem(STORAGE_KEYS.PRODUCTS);
    if (saved) {
      const parsed = JSON.parse(saved);
      if (Array.isArray(parsed) && parsed.length > 0) {
        // Merge with initial products so any newly added products & rich fields (gallery, highlights, specs) are preserved
        const initialMap = new Map(INITIAL_PRODUCTS.map((p) => [p.id, p]));
        const merged = INITIAL_PRODUCTS.map((initP) => {
          const existing = parsed.find((p) => p.id === initP.id || p.slug === initP.slug);
          return existing ? { ...initP, ...existing, highlights: initP.highlights || existing.highlights, features: initP.features || existing.features, specifications: initP.specifications || existing.specifications } : initP;
        });
        parsed.forEach((p) => {
          if (!initialMap.has(p.id) && !merged.some((m) => m.id === p.id || m.slug === p.slug)) {
            merged.push(p);
          }
        });
        return merged;
      }
    }
  } catch (e) {}
  return [...INITIAL_PRODUCTS];
};

export const saveLiveProducts = (products) => {
  try {
    localStorage.setItem(STORAGE_KEYS.PRODUCTS, JSON.stringify(products));
  } catch (e) {}
};

export const getLiveCategories = () => {
  try {
    const saved = localStorage.getItem(STORAGE_KEYS.CATEGORIES);
    if (saved) return JSON.parse(saved);
  } catch (e) {}
  return [...INITIAL_CATEGORIES];
};

export const saveLiveCategories = (categories) => {
  try {
    localStorage.setItem(STORAGE_KEYS.CATEGORIES, JSON.stringify(categories));
  } catch (e) {}
};

export const MOCK_CATEGORIES = getLiveCategories();
export const MOCK_PRODUCTS = getLiveProducts();

export const MOCK_COMPANIES = [
  {
    id: "comp-1",
    legalName: "Apex Global Wholesale Traders Pvt Ltd",
    tradingName: "Apex Global Wholesale",
    registrationNumber: "U01100MH2020PTC345678",
    taxId: "27AAACA1234A1Z1",
    country: "India",
    countryCode: "IN",
    status: "APPROVED",
    creditLimit: 1000000,
    availableCredit: 785000,
    paymentTerms: "NET_30",
    primaryContact: "Rajesh Kulkarni",
    email: "buyer@apexwholesale.in",
    phone: "+91 98200 12345",
    addresses: [
      { id: "addr-1", type: "SHIPPING", line1: "Warehouse 4, Global Logistics Park", city: "Navi Mumbai", state: "Maharashtra", postalCode: "400705", country: "India", isDefault: true },
      { id: "addr-2", type: "BILLING", line1: "Suite 302, Financial Hub", city: "Mumbai", state: "Maharashtra", postalCode: "400051", country: "India", isDefault: true },
    ],
    members: [
      { id: "mem-1", name: "Rajesh Kulkarni", email: "buyer@apexwholesale.in", role: "COMPANY_ADMIN", isPrimary: true },
      { id: "mem-2", name: "Sunil Verma", email: "procurement@apexwholesale.in", role: "COMPANY_BUYER", isPrimary: false },
    ],
    documents: [
      { id: "doc-1", name: "GST_Certificate_2026.pdf", type: "TAX_CERTIFICATE", status: "VERIFIED", uploadedAt: "2026-01-15T10:00:00Z" },
      { id: "doc-2", name: "Certificate_of_Incorporation.pdf", type: "BUSINESS_REGISTRATION", status: "VERIFIED", uploadedAt: "2026-01-15T10:05:00Z" },
    ],
  },
  {
    id: "comp-2",
    legalName: "Prime Logistics & Supplies LLC",
    tradingName: "Prime Supplies",
    registrationNumber: "US-DE-987654",
    taxId: "EIN-82-9384721",
    country: "United States",
    countryCode: "US",
    status: "UNDER_REVIEW",
    creditLimit: 50000,
    availableCredit: 50000,
    paymentTerms: "NET_15",
    primaryContact: "David Miller",
    email: "david@primesupplies.com",
    phone: "+1 214 555 0192",
    addresses: [
      { id: "addr-3", type: "SHIPPING", line1: "742 Commercial Way", city: "Dallas", state: "Texas", postalCode: "75201", country: "United States", isDefault: true },
    ],
    members: [
      { id: "mem-3", name: "David Miller", email: "david@primesupplies.com", role: "COMPANY_ADMIN", isPrimary: true },
    ],
    documents: [
      { id: "doc-3", name: "IRS_W9_Form.pdf", type: "TAX_CERTIFICATE", status: "UNDER_REVIEW", uploadedAt: "2026-02-10T14:30:00Z" },
      { id: "doc-4", name: "Delaware_LLC_Registration.pdf", type: "BUSINESS_REGISTRATION", status: "UNDER_REVIEW", uploadedAt: "2026-02-10T14:32:00Z" },
    ],
  },
];

export const MOCK_ORDERS = [
  {
    id: "ord-101",
    orderNumber: "ORD-20260228-8921",
    type: "B2C",
    createdAt: "2026-02-27T14:20:00Z",
    status: "DELIVERED",
    currency: "USD",
    symbol: "$",
    subtotal: 42.00,
    taxAmount: 449.82,
    shippingCost: 80,
    totalAmount: 49.99,
    itemsCount: 1,
    shippingAddress: {
      name: "Ramesh Sharma",
      line1: "Flat 402, Lotus Heights",
      city: "Bengaluru",
      state: "Karnataka",
      postalCode: "560001",
      country: "India",
    },
    items: [
      { id: "oi-1", name: "Royal Heritage Aged Basmati Rice (25 KG Sack)", sku: "FMCG-RICE-25KG", quantity: 1, unitPrice: 42.00, subtotal: 42.00, image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=400&q=80" },
    ],
    timeline: [
      { status: "PLACED", label: "Order Placed", date: "2026-02-27 14:20" },
      { status: "CONFIRMED", label: "Payment Confirmed", date: "2026-02-27 14:21" },
      { status: "PACKED", label: "Packed at Fulfillment Center", date: "2026-02-27 18:00" },
      { status: "SHIPPED", label: "Dispatched with Express Logistics", date: "2026-02-28 09:30" },
      { status: "DELIVERED", label: "Delivered Successfully", date: "2026-02-28 13:45" },
    ],
  },
  {
    id: "ord-102",
    orderNumber: "ORD-20260228-9410",
    poNumber: "PO-APEX-2026-04",
    type: "B2B",
    companyName: "Apex Global Wholesale Traders Pvt Ltd",
    createdAt: "2026-02-28T10:15:00Z",
    status: "PROCESSING",
    currency: "USD",
    symbol: "$",
    subtotal: 2800,
    taxAmount: 31500,
    shippingCost: 4500,
    totalAmount: 211000,
    paymentTerms: "NET_30",
    itemsCount: 100,
    shippingAddress: {
      name: "Apex Logistics Hub",
      line1: "Warehouse 4, Global Logistics Park",
      city: "Navi Mumbai",
      state: "Maharashtra",
      postalCode: "400705",
      country: "India",
    },
    items: [
      { id: "oi-2", name: "Royal Heritage Aged Basmati Rice (25 KG Sack)", sku: "FMCG-RICE-25KG", quantity: 100, unitPrice: 1750, subtotal: 2800, packaging: "2.5 Pallets (40 Sacks / Pallet)", image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=400&q=80" },
    ],
    timeline: [
      { status: "PLACED", label: "Purchase Order Received", date: "2026-02-28 10:15" },
      { status: "CONFIRMED", label: "Commercial Credit Verified (NET 30)", date: "2026-02-28 10:16" },
      { status: "PROCESSING", label: "Allocated to Mumbai Central Warehouse", date: "2026-02-28 11:00" },
    ],
  },
];

export const MOCK_QUOTES = [
  {
    id: "qte-201",
    quoteNumber: "QTE-20260228-1094",
    companyName: "Apex Global Wholesale Traders Pvt Ltd",
    status: "QUOTED",
    version: 2,
    createdAt: "2026-02-25T09:00:00Z",
    validUntil: "2026-03-15T23:59:59Z",
    currency: "USD",
    symbol: "$",
    subtotal: 3200,
    discountAmount: 9500,
    taxAmount: 32490,
    shippingCost: 5500,
    totalAmount: 3500,
    notes: "Consignment of 200 Bundles Corrugated Boxes & 100 Stretch Wrap Cartons.",
    items: [
      { id: "qi-1", name: "Heavy-Duty Corrugated Shipping Boxes (50 PK)", sku: "PKG-BOX-50PK", quantity: 200, unitPrice: 950, subtotal: 3200, requestedDeliveryDate: "2026-03-10" },
    ],
  },
];

export const MOCK_ADMIN_METRICS = {
  revenueToday: "$12,85,400",
  revenueGrowth: "+24.8%",
  activeOrdersCount: 68,
  b2bOrdersCount: 22,
  pendingCompanyVerifications: 4,
  pendingQuotesCount: 6,
  lowStockAlertsCount: 1,
  totalCustomers: 45200,
  totalB2BCompanies: 340,
};
