import { authRoutes } from "../modules/auth/index.js";
import { userRoutes } from "../modules/users/index.js";
import { customerRoutes } from "../modules/customers/index.js";
import { companyRoutes } from "../modules/companies/index.js";
import { businessVerificationRoutes } from "../modules/business-verification/index.js";
import { catalogRoutes } from "../modules/catalog/index.js";
import { categoryRoutes } from "../modules/categories/index.js";
import { brandRoutes } from "../modules/brands/index.js";
import { pricingRoutes } from "../modules/pricing/index.js";
import { geographyRoutes } from "../modules/geography/index.js";
import { inventoryRoutes } from "../modules/inventory/index.js";
import { cartRoutes } from "../modules/cart/index.js";
import { checkoutRoutes } from "../modules/checkout/index.js";
import { orderRoutes } from "../modules/orders/index.js";
import { bulkOrderRoutes } from "../modules/bulk-orders/index.js";
import { quoteRoutes } from "../modules/quotes/index.js";
import { paymentRoutes } from "../modules/payments/index.js";
import { taxRoutes } from "../modules/tax/index.js";
import { shippingRoutes } from "../modules/shipping/index.js";
import { reviewRoutes } from "../modules/reviews/index.js";
import { wishlistRoutes } from "../modules/wishlists/index.js";
import { notificationRoutes } from "../modules/notifications/index.js";
import { fileRoutes } from "../modules/files/index.js";
import { auditRoutes } from "../modules/audit/index.js";
import { adminRoutes } from "../modules/admin/index.js";

export default async function registerRoutes(fastify, options) {
  await fastify.register(authRoutes, { prefix: "/auth" });
  await fastify.register(userRoutes);
  await fastify.register(customerRoutes);
  await fastify.register(companyRoutes);
  await fastify.register(businessVerificationRoutes);
  await fastify.register(catalogRoutes);
  await fastify.register(categoryRoutes);
  await fastify.register(brandRoutes);
  await fastify.register(pricingRoutes);
  await fastify.register(geographyRoutes);
  await fastify.register(inventoryRoutes);
  await fastify.register(cartRoutes);
  await fastify.register(checkoutRoutes);
  await fastify.register(orderRoutes);
  await fastify.register(bulkOrderRoutes);
  await fastify.register(quoteRoutes);
  await fastify.register(paymentRoutes);
  await fastify.register(taxRoutes);
  await fastify.register(shippingRoutes);
  await fastify.register(reviewRoutes);
  await fastify.register(wishlistRoutes);
  await fastify.register(notificationRoutes);
  await fastify.register(fileRoutes);
  await fastify.register(auditRoutes);
  await fastify.register(adminRoutes);
}