export const ERROR_CODES = Object.freeze({
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHENTICATED: "UNAUTHENTICATED",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  
  // Auth
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  USER_INACTIVE: "USER_INACTIVE",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  TOKEN_INVALID: "TOKEN_INVALID",
  TOKEN_REVOKED: "TOKEN_REVOKED",

  // Company / B2B
  COMPANY_NOT_FOUND: "COMPANY_NOT_FOUND",
  COMPANY_NOT_APPROVED: "COMPANY_NOT_APPROVED",
  COMPANY_ALREADY_EXISTS: "COMPANY_ALREADY_EXISTS",
  DOCUMENT_REQUIRED: "DOCUMENT_REQUIRED",

  // Pricing & Catalog
  PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",
  VARIANT_NOT_FOUND: "VARIANT_NOT_FOUND",
  PRICE_NOT_FOUND: "PRICE_NOT_FOUND",
  MOQ_NOT_MET: "MOQ_NOT_MET",
  INVALID_PACKAGING: "INVALID_PACKAGING",

  // Inventory
  INSUFFICIENT_STOCK: "INSUFFICIENT_STOCK",
  RESERVATION_FAILED: "RESERVATION_FAILED",
  WAREHOUSE_NOT_FOUND: "WAREHOUSE_NOT_FOUND",

  // Cart & Checkout
  CART_EMPTY: "CART_EMPTY",
  INVALID_QUANTITY: "INVALID_QUANTITY",
  CHECKOUT_FAILED: "CHECKOUT_FAILED",
  IDEMPOTENCY_CONFLICT: "IDEMPOTENCY_CONFLICT",

  // Order
  ORDER_NOT_FOUND: "ORDER_NOT_FOUND",
  ORDER_CANNOT_BE_CANCELLED: "ORDER_CANNOT_BE_CANCELLED",

  // Quotes
  QUOTE_NOT_FOUND: "QUOTE_NOT_FOUND",
  QUOTE_EXPIRED: "QUOTE_EXPIRED",
  QUOTE_ALREADY_CONVERTED: "QUOTE_ALREADY_CONVERTED",
  QUOTE_NOT_ACCEPTED: "QUOTE_NOT_ACCEPTED",

  // Payment
  PAYMENT_FAILED: "PAYMENT_FAILED",
  REFUND_FAILED: "REFUND_FAILED",
  INVALID_PAYMENT_STATUS: "INVALID_PAYMENT_STATUS",
});
