export const ROLES = Object.freeze({
  CUSTOMER: "CUSTOMER",
  COMPANY_ADMIN: "COMPANY_ADMIN",
  COMPANY_BUYER: "COMPANY_BUYER",
  SALES: "SALES",
  INVENTORY_MANAGER: "INVENTORY_MANAGER",
  FINANCE: "FINANCE",
  ADMIN: "ADMIN",
  SUPER_ADMIN: "SUPER_ADMIN",
});
