export const ROUTES = {
  // Public B2C
  HOME: "/",
  PRODUCTS: "/products",
  PRODUCT_DETAILS: "/products/:slug",
  CATEGORY_PRODUCTS: "/categories/:slug",
  SEARCH: "/search",
  CART: "/cart",
  CHECKOUT: "/checkout",
  ORDERS: "/orders",
  ORDER_DETAILS: "/orders/:id",
  WISHLIST: "/wishlist",
  ACCOUNT: "/account",
  ACCOUNT_PROFILE: "/account/profile",
  ACCOUNT_ADDRESSES: "/account/addresses",
  LOGIN: "/login",
  REGISTER: "/register",
  REGISTER_BUSINESS: "/register-business",
  REGISTER_BUSINESS_SUCCESS: "/register-business/pending-approval",
  FORGOT_PASSWORD: "/forgot-password",
  CONTACT: "/contact",


  // B2B Wholesale Portal
  B2B: {
    ROOT: "/b2b",
    DASHBOARD: "/b2b/dashboard",
    CATALOG: "/b2b/catalog",
    PRODUCT_DETAILS: "/b2b/catalog/:slug",
    BULK_ORDER: "/b2b/bulk-order",
    QUOTES: "/b2b/quotes",
    QUOTE_DETAILS: "/b2b/quotes/:id",
    ORDERS: "/b2b/orders",
    ORDER_DETAILS: "/b2b/orders/:id",
    COMPANY: "/b2b/company",
    COMPANY_PROFILE: "/b2b/company/profile",
    COMPANY_DOCUMENTS: "/b2b/company/documents",
    COMPANY_MEMBERS: "/b2b/company/members",
    ACCOUNT: "/b2b/account",
  },

  // Admin Dashboard
  ADMIN: {
    ROOT: "/admin",
    DASHBOARD: "/admin/dashboard",
    USERS: "/admin/users",
    COMPANIES: "/admin/companies",
    COMPANY_DETAILS: "/admin/companies/:id",
    BUSINESS_APPLICATIONS: "/admin/business-applications",
    PRODUCTS: "/admin/products",
    PRODUCT_NEW: "/admin/products/new",
    PRODUCT_EDIT: "/admin/products/:id/edit",
    BULK_PRODUCTS: "/admin/bulk-products",
    CATEGORIES: "/admin/categories",
    INVENTORY: "/admin/inventory",
    ORDERS: "/admin/orders",
    RETAIL_ORDERS: "/admin/retail-orders",
    BULK_ORDERS: "/admin/bulk-orders",
    QUOTES: "/admin/quotes",
    PAYMENTS: "/admin/payments",
    REPORTS: "/admin/reports",
    AUDIT_LOGS: "/admin/audit-logs",
  },
};
