import "dotenv/config";

export const env = {
  port: Number(process.env.PORT || 3000),
  databaseUrl: process.env.DATABASE_URL,
  jwtSecret: process.env.JWT_SECRET || "development-secret",
  jwtExpiresIn: process.env.JWT_EXPIRES_IN || "7d",
  passwordResetExpiresMinutes: Number(process.env.PASSWORD_RESET_EXPIRES_MINUTES) || 30,
  emailVerificationExpiresMinutes: Number(process.env.EMAIL_VERIFICATION_EXPIRES_MINUTES) || 60,
  emailProvider: process.env.EMAIL_PROVIDER || "console",
  emailFrom: process.env.EMAIL_FROM,
  resendApiKey: process.env.RESEND_API_KEY,
  appUrl: process.env.APP_URL || "http://localhost:3000",
  clientUrl: process.env.CLIENT_URL || "http://localhost:5173",
  awsRegion: process.env.AWS_REGION || "us-east-1",
  smsProvider: process.env.SMS_PROVIDER || "console",
  smtpHost: process.env.SMTP_HOST,
  smtpPort: Number(process.env.SMTP_PORT) || 587,
  smtpSecure: process.env.SMTP_SECURE === "true",
  smtpUser: process.env.SMTP_USER,
  smtpPassword: process.env.SMTP_PASSWORD,
  nodeEnv: process.env.NODE_ENV || "development",
  uploadProvider: process.env.UPLOAD_PROVIDER || "local",
  uploadDir: process.env.UPLOAD_DIR || "uploads",
  assetDir: process.env.ASSET_DIR || "assets",
  assetPublicUrl: process.env.ASSET_PUBLIC_URL || `${process.env.APP_URL || "http://localhost:3000"}/assets`,
  uploadMaxFileSize: Number(process.env.UPLOAD_MAX_FILE_SIZE) || 10 * 1024 * 1024,
  imageMaxWidth: Number(process.env.IMAGE_MAX_WIDTH) || 1920,
  imageMaxHeight: Number(process.env.IMAGE_MAX_HEIGHT) || 1920,
  imageWebpQuality: Number(process.env.IMAGE_WEBP_QUALITY) || 82,
  uploadAllowedMimeTypes: (process.env.UPLOAD_ALLOWED_MIME_TYPES || "image/jpeg,image/png,image/webp,application/pdf")
    .split(",").map((value) => value.trim()).filter(Boolean),
  s3Bucket: process.env.S3_BUCKET,
  s3Region: process.env.S3_REGION || "us-east-1",
  s3Endpoint: process.env.S3_ENDPOINT,
  s3ForcePathStyle: process.env.S3_FORCE_PATH_STYLE === "true"
};
